version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4
    steps:
      - checkout      
      - setup_remote_docker
      - restore_cache:
          key: build-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: build-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths: ['.']

workflows:
  version: 2
  build-deploy:
    jobs:
      - build